services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: capshop-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: capshop
      RABBITMQ_DEFAULT_PASS: capshop123!
    volumes:
      - capshop-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - capshop-network

  redis:
    image: redis:7-alpine
    container_name: capshop-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - capshop-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - capshop-network

networks:
  capshop-network:
    driver: bridge

volumes:
  capshop-rabbitmq-data:
  capshop-redis-data: